CREATE TABLE Table1 (Col1 INT NOT NULL UNIQUE) 
GO 

BEGIN TRAN

INSERT INTO Table1 VALUES(1)
INSERT INTO Table1 VALUES(2)

UPDATE Table1 SET Col1 = 2 WHERE Col1 = 1 -- WILL CAUSE DUPLICATE KEY

COMMIT

GO 

-- AND THEN WE DO SELECT
SELECT * FROM Table1
