CREATE TABLE t3 (a INT NOT NULL UNIQUE)
GO

BEGIN TRAN

INSERT INTO t3 VALUES (1)
INSERT INTO t3 VALUES (1) -- WILL CAUSE DUPLICATE KEY ERROR 

IF @@ERROR = 2627
BEGIN
    PRINT 'Constraint violation, rolling back!'
	ROLLBACK 
END
ELSE
    COMMIT
	
GO